INSERT INTO "Storage"."Records" ("accessionNumber","recordSet", "identifier", "title", "maintainerID", "validatorID", "profile", "updateDate", "isValidated", "isPublished", "type")  VALUES (10, 'CSWCat', '000068C3-3B49-C671-89CF-10A39BB1B652', '000068C3-3B49-C671-89CF-10A39BB1B652', 'admin', 'admin', 'inspire_core_service', '2009-07-01', 0, 1, 'NORMALFORM');
INSERT INTO "Storage"."Records" ("accessionNumber","recordSet", "identifier", "title", "maintainerID", "validatorID", "profile", "updateDate", "isValidated", "isPublished", "type")  VALUES (11, 'CSWCat', 'urn:uuid:3e195454-42e8-11dd-8329-00e08157d076','urn:uuid:3e195454-42e8-11dd-8329-00e08157d076', 'admin', 'admin', 'inspire_core_service', '2009-07-01', 0, 1, 'NORMALFORM');

INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject', 1, 'ExtrinsicObject', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:name', 1, 'InternationalString', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:name.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:name:localizedString', 1, 'LocalizedString', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:name.1:localizedString.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:description', 1, 'InternationalString', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:description.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:description:localizedString', 1, 'LocalizedString', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot', 1, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot', 2, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.2');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:valueList.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot', 3, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.3');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:valueList.1');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot', 4, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.4');
INSERT INTO "Storage"."Values" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:valueList.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject', 1, 'ExtrinsicObject', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:description', 1, 'InternationalString', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:description.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:description:localizedString', 1, 'LocalizedString', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot', 1, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot', 2, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.2');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:valueList.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot', 3, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.3');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:valueList.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot', 4, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.4');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:valueList.1');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot', 5, 'Slot', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.5');
INSERT INTO "Storage"."Values" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList', 1, 'ValueList', 'Ebrim v2.5', 'Ebrim v2.5:ExtrinsicObject.1:slot.5:valueList.1');


INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:mimeType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:mimeType.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:isOpaque', 1, 'Boolean', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:isOpaque.1', 'false');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:majorVersion', 1, 'Integer', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:majorVersion.1', '1');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:minorVersion', 1, 'Integer', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:minorVersion.1', '0');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:stability', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:stability.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:userVersion', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:userVersion.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:name:localizedString:lang', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:name.1:localizedString.1:lang.1', 'en-US');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:name:localizedString:charset', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:name.1:localizedString.1:charset.1', 'UTF-8');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:name:localizedString:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:name.1:localizedString.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:description:localizedString:lang', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1:lang.1', 'en-US');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:description:localizedString:charset', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1:charset.1', 'UTF-8');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:description:localizedString:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.1', '0.0');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:name.1', 'Rank');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:valueList.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:name.1', 'Content Start Date');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:valueList.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:name.1', 'Content End Date');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:valueList.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:name.1', 'Modification Date');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:id', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:id.1', '000068C3-3B49-C671-89CF-10A39BB1B652');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:objectType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:objectType.1', 'Geometry');
INSERT INTO "Storage"."TextValues" VALUES (10, 'Ebrim v2.5:ExtrinsicObject:status', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:status.1', 'urn:oasis:names:tc:ebxml-regrep:StatusType:Submitted');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:mimeType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:mimeType.1', 'application/octet-stream');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:isOpaque', 1, 'Boolean', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:isOpaque.1', 'false');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:majorVersion', 1, 'Integer', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:majorVersion.1', '1');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:minorVersion', 1, 'Integer', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:minorVersion.1', '0');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:stability', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:stability.1', 'Static');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:description:localizedString:lang', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1:lang.1', 'en-US');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:description:localizedString:charset', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1:charset.1', 'UTF-8');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:description:localizedString:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:description.1:localizedString.1:value.1', 'CubeSERV layers');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.1', 'AUTO:42001');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 2, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.2', 'AUTO:42002');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 3, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.3', 'AUTO:42003');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 4, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.4', 'AUTO:42004');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 5, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.5', 'CRS:27');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 6, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.6', 'CRS:83');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 7, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.7', 'CRS:84');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 8, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.8', 'EPSG:100001');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 9, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.9', 'EPSG:100002');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 10, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.10', 'EPSG:32746');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 11, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.11', 'EPSG:32747');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 12, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:valueList.1:value.12', 'EPSG:900913');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:name.1', 'CRS');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:slotType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.1:slotType.1', 'string');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:valueList.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 2, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:valueList.1:value.2', '');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:name.1', 'Envelope');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:slotType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.2:slotType.1', 'geometry');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:valueList.1:value.1', '');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 2, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:valueList.1:value.2', '');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:name.1', 'Footprint');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:slotType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.3:slotType.1', 'geometry');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:valueList.1:value.1', '0');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:name.1', 'Queryable');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:slotType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.4:slotType.1', 'integer');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:valueList:value', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.5:valueList.1:value.1', 'CubeSERV layers');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:name', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.5:name.1', 'Title');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:slot:slotType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:slot.5:slotType.1', 'string');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:id', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:id.1', 'urn:uuid:3e195454-42e8-11dd-8329-00e08157d076');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:home', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:home.1', 'http://demo.cubewerx.com/demo/cubeserv/cubeserv.cgi');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:objectType', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:objectType.1', 'Theme');
INSERT INTO "Storage"."TextValues" VALUES (11, 'Ebrim v2.5:ExtrinsicObject:status', 1, 'CharacterString', 'ISO 19103', 'Ebrim v2.5:ExtrinsicObject.1:status.1', 'Approved');

