/*
 *    Constellation - An open source and standard compliant SDI
 *    http://www.constellation-sdi.org
 *
 *    (C) 2013, Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.constellation.swing;

import java.awt.Dimension;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import org.constellation.generic.database.Automatic;
import org.constellation.generic.database.BDD;

/**
 *
 * @author Guilhem Legal (Geomatys)
 */
public class JCswMdwEditPane extends JServiceEditionPane {

    /**
     * Creates new form JCswMdwEditPane
     */
    public JCswMdwEditPane(final Automatic configuration) {
        initComponents();
        if (configuration != null) {
            final BDD bdd = configuration.getBdd();
            if (bdd != null) {
                if (bdd.getClassName() != null) {
                    guiDriver.setText(bdd.getClassName());
                }
                if (bdd.getConnectURL() != null) {
                    guiDbURL.setText(bdd.getConnectURL());
                }
                if (bdd.getUser()!= null) {
                    guiUser.setText(bdd.getUser());
                }
                if (bdd.getPassword()!= null) {
                    guiPwd.setText(bdd.getPassword());
                }
            }
            guiIndexPubCheck.setSelected(configuration.getIndexOnlyPublishedMetadata());
            guiIndexInterCheck.setSelected(configuration.getIndexInternalRecordset());
            if (configuration.getProfileValue() != null) {
                guiProfileCombo.setSelectedItem(configuration.getProfileValue());
            }
        }
        
    }
    
    @Override
    public Automatic getConfiguration() {
        final String className  = guiDriver.getText();
        final String connectURL = guiDbURL.getText();
        final String user       = guiUser.getText();
        final String password   = new String(guiPwd.getPassword());
        final BDD bdd           = new BDD(className, connectURL, user, password);
        final Automatic configuration = new Automatic("mdweb", bdd);
        configuration.setIndexOnlyPublishedMetadata(guiIndexPubCheck.isSelected());
        configuration.setIndexInternalRecordset(guiIndexInterCheck.isSelected());
        configuration.setProfile((String)guiProfileCombo.getSelectedItem());
        return configuration;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        guiDriver = new JTextField();
        jLabel2 = new JLabel();
        guiDbURL = new JTextField();
        jLabel3 = new JLabel();
        guiUser = new JTextField();
        jLabel4 = new JLabel();
        guiPwd = new JPasswordField();
        jLabel5 = new JLabel();
        guiIndexPubCheck = new JCheckBox();
        jLabel6 = new JLabel();
        guiIndexInterCheck = new JCheckBox();
        jLabel7 = new JLabel();
        guiProfileCombo = new JComboBox();

        setMinimumSize(new Dimension(562, 278));

        ResourceBundle bundle = ResourceBundle.getBundle("org/constellation/swing/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("driverClass")); // NOI18N

        jLabel2.setText(bundle.getString("dbUrl")); // NOI18N

        jLabel3.setText(bundle.getString("dbUser")); // NOI18N

        jLabel4.setText(bundle.getString("dbPwd")); // NOI18N

        jLabel5.setText(bundle.getString("indexOnlyPublish")); // NOI18N

        jLabel6.setText(bundle.getString("indexInternal")); // NOI18N

        jLabel7.setText(bundle.getString("profil")); // NOI18N

        guiProfileCombo.setModel(new DefaultComboBoxModel(new String[] { "discovery", "transactional" }));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(guiDriver, GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(guiDbURL)
                    .addComponent(guiUser)
                    .addComponent(guiPwd)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(guiIndexInterCheck)
                            .addComponent(guiIndexPubCheck))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(guiProfileCombo, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(guiDriver, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(guiDbURL, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(guiUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(guiPwd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(guiIndexPubCheck))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(guiIndexInterCheck))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(guiProfileCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField guiDbURL;
    private JTextField guiDriver;
    private JCheckBox guiIndexInterCheck;
    private JCheckBox guiIndexPubCheck;
    private JComboBox guiProfileCombo;
    private JPasswordField guiPwd;
    private JTextField guiUser;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
