/*
 *    Constellation - An open source and standard compliant SDI
 *    http://www.constellation-sdi.org
 *
 *    (C) 2013, Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.constellation.swing;

import java.util.ArrayList;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import org.apache.sis.util.logging.Logging;
import org.constellation.admin.service.ConstellationServer;
import org.constellation.configuration.ProcessFactory;
import org.jdesktop.swingx.combobox.ListComboBoxModel;
import org.openide.util.NbBundle;

/**
 *
 * @author Guilhem Legal (Geomatys)
 */
public class JEditProcessFactoryPane extends javax.swing.JPanel {

    private static final Logger LOGGER = Logging.getLogger(JEditProcessFactoryPane.class);

    private static final String EMPTY_ITEM = "empty";

    private ProcessFactoryModel processFactoryModel;

    /**
     * Creates new form JEditProcessFactoryPane
     * @param server
     * @param processFactoryModel
     */
    public JEditProcessFactoryPane(final ConstellationServer server, final ProcessFactoryModel processFactoryModel) {
        this.processFactoryModel = processFactoryModel;
        initComponents();

        processFactoryComboBox.setModel(new ListComboBoxModel(new ArrayList<>(server.tasks.listProcessFactories().getList())));
    }

    public ProcessFactoryModel getProcessFactoryEntry() {
        if (processFactoryModel == null) {
            processFactoryModel = new ProcessFactoryModel(new ProcessFactory());
        }
        processFactoryModel.getFactory().setAutorityCode((String)processFactoryComboBox.getSelectedItem());
        processFactoryModel.getFactory().setLoadAll(Boolean.TRUE);
        
        return processFactoryModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        processFactoryComboBox = new JComboBox();

        jLabel1.setText(NbBundle.getMessage(JEditProcessFactoryPane.class, "processFactory")); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processFactoryComboBox, 0, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(processFactoryComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JComboBox processFactoryComboBox;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param server
     * @param processFactory
     * @return 
     */
    public static ProcessFactoryModel showDialog(final ConstellationServer server, final ProcessFactoryModel processFactory){
        
        final JEditProcessFactoryPane pane = new JEditProcessFactoryPane(server, processFactory);
                
        int res = JOptionPane.showOptionDialog(null, new Object[]{pane}, 
                ProcessFactoryRowModel.BUNDLE.getString("createProcessFactoryMsg"),
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, 
                null);
        
        ProcessFactoryModel processFactoryModel = null;
        if (res != JOptionPane.CANCEL_OPTION && res != JOptionPane.CLOSED_OPTION) {
            processFactoryModel = pane.getProcessFactoryEntry();
        }
        return processFactoryModel;
    }
}
