/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.constellation.swing;

import org.constellation.admin.service.ConstellationServer;

/**
 *
 * @author guilhem
 */
public class JUtilsPane extends javax.swing.JPanel {

    private final FrameDisplayer displayer;
    private final ConstellationServer cstl;
    
    /**
     * Creates new form JUtilsPane
     * @param cstl
     * @param displayer
     */
    public JUtilsPane(final ConstellationServer cstl, final FrameDisplayer displayer) {
        initComponents();
        if(displayer == null){
            this.displayer = new DefaultFrameDisplayer();
        } else {
            this.displayer = displayer;
        }
        this.cstl = cstl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        epsgDbButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(epsgDbButton, org.openide.util.NbBundle.getMessage(JUtilsPane.class, "buildEpsgDatabase")); // NOI18N
        epsgDbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsgDbButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(epsgDbButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(epsgDbButton)
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void epsgDbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epsgDbButtonActionPerformed
        displayer.display(new JEpsgDbCreationPane());
    }//GEN-LAST:event_epsgDbButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton epsgDbButton;
    // End of variables declaration//GEN-END:variables
}
