//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.19 at 04:54:59 PM CDT 
//

package net.seagis.xacml.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for AttributeAssignmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeAssignmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}AttributeValueType">
 *       &lt;attribute name="AttributeId" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeAssignmentType")
public class AttributeAssignmentType extends AttributeValueType
{

   @XmlAttribute(name = "AttributeId", required = true)
   @XmlSchemaType(name = "anyURI")
   protected String attributeId;

   /**
    * Gets the value of the attributeId property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getAttributeId()
   {
      return attributeId;
   }

   /**
    * Sets the value of the attributeId property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setAttributeId(String value)
   {
      this.attributeId = value;
   }

}
