//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.19 at 04:54:59 PM CDT 
//

package net.seagis.xacml.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ResourceMatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceMatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}AttributeValue"/>
 *         &lt;choice>
 *           &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}ResourceAttributeDesignator"/>
 *           &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}AttributeSelector"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="MatchId" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceMatchType", propOrder =
{"attributeValue", "resourceAttributeDesignator", "attributeSelector"})
public class ResourceMatchType
{

   @XmlElement(name = "AttributeValue", required = true)
   protected AttributeValueType attributeValue;

   @XmlElement(name = "ResourceAttributeDesignator")
   protected AttributeDesignatorType resourceAttributeDesignator;

   @XmlElement(name = "AttributeSelector")
   protected AttributeSelectorType attributeSelector;

   @XmlAttribute(name = "MatchId", required = true)
   @XmlSchemaType(name = "anyURI")
   protected String matchId;

   /**
    * Gets the value of the attributeValue property.
    * 
    * @return
    *     possible object is
    *     {@link AttributeValueType }
    *     
    */
   public AttributeValueType getAttributeValue()
   {
      return attributeValue;
   }

   /**
    * Sets the value of the attributeValue property.
    * 
    * @param value
    *     allowed object is
    *     {@link AttributeValueType }
    *     
    */
   public void setAttributeValue(AttributeValueType value)
   {
      this.attributeValue = value;
   }

   /**
    * Gets the value of the resourceAttributeDesignator property.
    * 
    * @return
    *     possible object is
    *     {@link AttributeDesignatorType }
    *     
    */
   public AttributeDesignatorType getResourceAttributeDesignator()
   {
      return resourceAttributeDesignator;
   }

   /**
    * Sets the value of the resourceAttributeDesignator property.
    * 
    * @param value
    *     allowed object is
    *     {@link AttributeDesignatorType }
    *     
    */
   public void setResourceAttributeDesignator(AttributeDesignatorType value)
   {
      this.resourceAttributeDesignator = value;
   }

   /**
    * Gets the value of the attributeSelector property.
    * 
    * @return
    *     possible object is
    *     {@link AttributeSelectorType }
    *     
    */
   public AttributeSelectorType getAttributeSelector()
   {
      return attributeSelector;
   }

   /**
    * Sets the value of the attributeSelector property.
    * 
    * @param value
    *     allowed object is
    *     {@link AttributeSelectorType }
    *     
    */
   public void setAttributeSelector(AttributeSelectorType value)
   {
      this.attributeSelector = value;
   }

   /**
    * Gets the value of the matchId property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getMatchId()
   {
      return matchId;
   }

   /**
    * Sets the value of the matchId property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setMatchId(String value)
   {
      this.matchId = value;
   }

}
