//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.19 at 04:54:59 PM CDT 
//

package net.seagis.xacml.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TargetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TargetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Subjects" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Resources" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Actions" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Environments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetType", propOrder =
{"subjects", "resources", "actions", "environments"})
public class TargetType
{

   @XmlElement(name = "Subjects")
   protected SubjectsType subjects;

   @XmlElement(name = "Resources")
   protected ResourcesType resources;

   @XmlElement(name = "Actions")
   protected ActionsType actions;

   @XmlElement(name = "Environments")
   protected EnvironmentsType environments;

   /**
    * Gets the value of the subjects property.
    * 
    * @return
    *     possible object is
    *     {@link SubjectsType }
    *     
    */
   public SubjectsType getSubjects()
   {
      return subjects;
   }

   /**
    * Sets the value of the subjects property.
    * 
    * @param value
    *     allowed object is
    *     {@link SubjectsType }
    *     
    */
   public void setSubjects(SubjectsType value)
   {
      this.subjects = value;
   }

   /**
    * Gets the value of the resources property.
    * 
    * @return
    *     possible object is
    *     {@link ResourcesType }
    *     
    */
   public ResourcesType getResources()
   {
      return resources;
   }

   /**
    * Sets the value of the resources property.
    * 
    * @param value
    *     allowed object is
    *     {@link ResourcesType }
    *     
    */
   public void setResources(ResourcesType value)
   {
      this.resources = value;
   }

   /**
    * Gets the value of the actions property.
    * 
    * @return
    *     possible object is
    *     {@link ActionsType }
    *     
    */
   public ActionsType getActions()
   {
      return actions;
   }

   /**
    * Sets the value of the actions property.
    * 
    * @param value
    *     allowed object is
    *     {@link ActionsType }
    *     
    */
   public void setActions(ActionsType value)
   {
      this.actions = value;
   }

   /**
    * Gets the value of the environments property.
    * 
    * @return
    *     possible object is
    *     {@link EnvironmentsType }
    *     
    */
   public EnvironmentsType getEnvironments()
   {
      return environments;
   }

   /**
    * Sets the value of the environments property.
    * 
    * @param value
    *     allowed object is
    *     {@link EnvironmentsType }
    *     
    */
   public void setEnvironments(EnvironmentsType value)
   {
      this.environments = value;
   }

}
