/*
 *    Constellation - An open source and standard compliant SDI
 *    http://www.constellation-sdi.org
 *
 *    (C) 2005, Institut de Recherche pour le DÃƒÂ©veloppement
 *    (C) 2007 - 2008, Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.constellation.generic.edmo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "edmo_webserviceSoap", targetNamespace = "ns_ws_edmo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EdmoWebserviceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_get_list", action = "ns_ws_edmo/ws_edmo_get_list")
    @WebResult(name = "ws_edmo_get_listResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_get_list", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetList")
    @ResponseWrapper(localName = "ws_edmo_get_listResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetListResponse")
    public String wsEdmoGetList();

    /**
     * 
     * @param nCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_get_detail", action = "ns_ws_edmo/ws_edmo_get_detail")
    @WebResult(name = "ws_edmo_get_detailResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_get_detail", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetDetail")
    @ResponseWrapper(localName = "ws_edmo_get_detailResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetDetailResponse")
    public String wsEdmoGetDetail(
        @WebParam(name = "n_code", targetNamespace = "ns_ws_edmo")
        String nCode);

    /**
     * 
     * @param cName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_name_to_code", action = "ns_ws_edmo/ws_edmo_name_to_code")
    @WebResult(name = "ws_edmo_name_to_codeResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_name_to_code", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoNameToCode")
    @ResponseWrapper(localName = "ws_edmo_name_to_codeResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoNameToCodeResponse")
    public String wsEdmoNameToCode(
        @WebParam(name = "c_name", targetNamespace = "ns_ws_edmo")
        String cName);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_active_countries", action = "ns_ws_edmo/ws_edmo_active_countries")
    @WebResult(name = "ws_edmo_active_countriesResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_active_countries", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoActiveCountries")
    @ResponseWrapper(localName = "ws_edmo_active_countriesResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoActiveCountriesResponse")
    public String wsEdmoActiveCountries();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_active_characters", action = "ns_ws_edmo/ws_edmo_active_characters")
    @WebResult(name = "ws_edmo_active_charactersResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_active_characters", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoActiveCharacters")
    @ResponseWrapper(localName = "ws_edmo_active_charactersResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoActiveCharactersResponse")
    public String wsEdmoActiveCharacters();

    /**
     * 
     * @param freeSearch
     * @param upperLeftLong
     * @param shortList
     * @param firstCharacter
     * @param lowerRightLong
     * @param lastUpdate
     * @param upperLeftLat
     * @param lowerRightLat
     * @param countryNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_get_query", action = "ns_ws_edmo/ws_edmo_get_query")
    @WebResult(name = "ws_edmo_get_queryResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_get_query", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetQuery")
    @ResponseWrapper(localName = "ws_edmo_get_queryResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetQueryResponse")
    public String wsEdmoGetQuery(
        @WebParam(name = "short_list", targetNamespace = "ns_ws_edmo")
        String shortList,
        @WebParam(name = "free_search", targetNamespace = "ns_ws_edmo")
        String freeSearch,
        @WebParam(name = "first_character", targetNamespace = "ns_ws_edmo")
        String firstCharacter,
        @WebParam(name = "country_number", targetNamespace = "ns_ws_edmo")
        String countryNumber,
        @WebParam(name = "upper_left_lat", targetNamespace = "ns_ws_edmo")
        String upperLeftLat,
        @WebParam(name = "upper_left_long", targetNamespace = "ns_ws_edmo")
        String upperLeftLong,
        @WebParam(name = "lower_right_lat", targetNamespace = "ns_ws_edmo")
        String lowerRightLat,
        @WebParam(name = "lower_right_long", targetNamespace = "ns_ws_edmo")
        String lowerRightLong,
        @WebParam(name = "last_update", targetNamespace = "ns_ws_edmo")
        String lastUpdate);

    /**
     * 
     * @param collatorId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ws_edmo_get_list_collator", action = "ns_ws_edmo/ws_edmo_get_list_collator")
    @WebResult(name = "ws_edmo_get_list_collatorResult", targetNamespace = "ns_ws_edmo")
    @RequestWrapper(localName = "ws_edmo_get_list_collator", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetListCollator")
    @ResponseWrapper(localName = "ws_edmo_get_list_collatorResponse", targetNamespace = "ns_ws_edmo", className = "ns_ws_edmo.WsEdmoGetListCollatorResponse")
    public String wsEdmoGetListCollator(
        @WebParam(name = "collator_id", targetNamespace = "ns_ws_edmo")
        int collatorId);

}
