//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.02 at 03:45:52 PM CET 
//


package org.constellation.wmts.v100;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.constellation.ows.v110.CapabilitiesBaseType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ows/1.1}CapabilitiesBaseType">
 *       &lt;sequence>
 *         &lt;element name="Contents" type="{http://www.opengis.net/wmts/1.0}ContentsType"/>
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}Themes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contents",
    "themes"
})
@XmlRootElement(name = "Capabilities")
public class Capabilities
    extends CapabilitiesBaseType
{

    @XmlElement(name = "Contents", required = true)
    protected ContentsType contents;
    @XmlElement(name = "Themes")
    protected Themes themes;

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link ContentsType }
     *     
     */
    public ContentsType getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentsType }
     *     
     */
    public void setContents(ContentsType value) {
        this.contents = value;
    }

    /**
     * Metadata describing a theme hierarchy for the layers
     * 
     * @return
     *     possible object is
     *     {@link Themes }
     *     
     */
    public Themes getThemes() {
        return themes;
    }

    /**
     * Metadata describing a theme hierarchy for the layers
     * 
     * @param value
     *     allowed object is
     *     {@link Themes }
     *     
     */
    public void setThemes(Themes value) {
        this.themes = value;
    }

}
