//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.02 at 03:45:52 PM CET 
//


package org.constellation.wmts.v100;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.constellation.ows.v110.ContentsBaseType;


/**
 * <p>Java class for ContentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ows/1.1}ContentsBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/wmts/1.0}TileMatrixSet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentsType", propOrder = {
    "tileMatrixSet"
})
@XmlRootElement(name="ContentsType")
public class ContentsType
    extends ContentsBaseType
{

    @XmlElement(name = "TileMatrixSet")
    protected List<TileMatrixSet> tileMatrixSet;

    /**
     * A description of the geometry of a tile cut Gets the value of the tileMatrixSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tileMatrixSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTileMatrixSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TileMatrixSet }
     * 
     * 
     */
    public List<TileMatrixSet> getTileMatrixSet() {
        if (tileMatrixSet == null) {
            tileMatrixSet = new ArrayList<TileMatrixSet>();
        }
        return this.tileMatrixSet;
    }

}
