//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.13 at 04:28:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengeospatial.net/sos/0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns = { @javax.xml.bind.annotation.XmlNs(prefix = "sos", namespaceURI= "http://www.opengeospatial.net/sos/0"),
          @javax.xml.bind.annotation.XmlNs(prefix = "gml", namespaceURI= "http://www.opengis.net/gml/3.2"),
          @javax.xml.bind.annotation.XmlNs(prefix = "ogc", namespaceURI= "http://www.opengis.net/ogc"),
          @javax.xml.bind.annotation.XmlNs(prefix = "swe", namespaceURI= "http://www.opengis.net/swe/1.0"),
          @javax.xml.bind.annotation.XmlNs(prefix = "ows", namespaceURI= "http://www.opengis.net/ows/1.1"),
          @javax.xml.bind.annotation.XmlNs(prefix = "om", namespaceURI= "http://www.opengis.net/om/1.0"),
          @javax.xml.bind.annotation.XmlNs(prefix = "sml", namespaceURI= "http://www.opengis.net/sensorML/1.0"),
          @javax.xml.bind.annotation.XmlNs(prefix = "sg", namespaceURI= "http://catalog.seagis.net")})
package net.seagis.sos;
