//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.11 at 08:02:10 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengis.net/ows/1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.seagis.ows;
