//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.13 at 04:28:10 PM CEST 
//


package net.seagis.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BinarySpatialOpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BinarySpatialOpType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ogc}SpatialOpsType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}AbstractGeometry"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}AbstractGeometricPrimitive"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}Point"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}AbstractImplicitGeometry"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}Envelope"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}EnvelopeWithTimePeriod"/>
 *           &lt;element ref="{http://www.opengis.net/ogc}PropertyName"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinarySpatialOpType", propOrder = {
    "abstractGeometryOrAbstractGeometricPrimitiveOrPoint"
})
@XmlSeeAlso({PropertyNameType.class})
public class BinarySpatialOpType
    extends SpatialOpsType
{

    @XmlElementRefs({
        @XmlElementRef(name = "Envelope", namespace = "http://www.opengis.net/gml/3.2", type = JAXBElement.class),
        @XmlElementRef(name = "AbstractGeometry", namespace = "http://www.opengis.net/gml/3.2", type = JAXBElement.class),
        @XmlElementRef(name = "PropertyName", namespace = "http://www.opengis.net/ogc", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> abstractGeometryOrAbstractGeometricPrimitiveOrPoint;

    /**
     * Gets the value of the abstractGeometryOrAbstractGeometricPrimitiveOrPoint property.
     */
    public List<JAXBElement<?>> getAbstractGeometryOrAbstractGeometricPrimitiveOrPoint() {
        if (abstractGeometryOrAbstractGeometricPrimitiveOrPoint == null) {
            abstractGeometryOrAbstractGeometricPrimitiveOrPoint = new ArrayList<JAXBElement<?>>();
        }
        return this.abstractGeometryOrAbstractGeometricPrimitiveOrPoint;
    }

}
