//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.13 at 04:28:10 PM CEST 
//


package net.seagis.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for TemporalOperatorNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TemporalOperatorNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="T_After"/>
 *     &lt;enumeration value="T_Before"/>
 *     &lt;enumeration value="T_Begins"/>
 *     &lt;enumeration value="T_BegunBy"/>
 *     &lt;enumeration value="T_Contains"/>
 *     &lt;enumeration value="T_During"/>
 *     &lt;enumeration value="T_Equals"/>
 *     &lt;enumeration value="T_Overlaps"/>
 *     &lt;enumeration value="T_Meets"/>
 *     &lt;enumeration value="T_OverlappedBy"/>
 *     &lt;enumeration value="T_MetBy"/>
 *     &lt;enumeration value="T_EndedBy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TemporalOperatorNameType {

    @XmlEnumValue("T_After")
    T_AFTER("T_After"),
    @XmlEnumValue("T_Before")
    T_BEFORE("T_Before"),
    @XmlEnumValue("T_Begins")
    T_BEGINS("T_Begins"),
    @XmlEnumValue("T_BegunBy")
    T_BEGUN_BY("T_BegunBy"),
    @XmlEnumValue("T_Contains")
    T_CONTAINS("T_Contains"),
    @XmlEnumValue("T_During")
    T_DURING("T_During"),
    @XmlEnumValue("T_Equals")
    T_EQUALS("T_Equals"),
    @XmlEnumValue("T_Overlaps")
    T_OVERLAPS("T_Overlaps"),
    @XmlEnumValue("T_Meets")
    T_MEETS("T_Meets"),
    @XmlEnumValue("T_OverlappedBy")
    T_OVERLAPPED_BY("T_OverlappedBy"),
    @XmlEnumValue("T_MetBy")
    T_MET_BY("T_MetBy"),
    @XmlEnumValue("T_EndedBy")
    T_ENDED_BY("T_EndedBy");
    private final String value;

    TemporalOperatorNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TemporalOperatorNameType fromValue(String v) {
        for (TemporalOperatorNameType c: TemporalOperatorNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
