//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.19 at 04:54:59 PM CDT 
//

package net.seagis.xacml.context;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ResourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:context:schema:os}ResourceContent" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:context:schema:os}Attribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceType", propOrder =
{"resourceContent", "attribute"})
public class ResourceType
{

   @XmlElement(name = "ResourceContent")
   protected ResourceContentType resourceContent;

   @XmlElement(name = "Attribute")
   protected List<AttributeType> attribute;

   /**
    * Gets the value of the resourceContent property.
    * 
    * @return
    *     possible object is
    *     {@link ResourceContentType }
    *     
    */
   public ResourceContentType getResourceContent()
   {
      return resourceContent;
   }

   /**
    * Sets the value of the resourceContent property.
    * 
    * @param value
    *     allowed object is
    *     {@link ResourceContentType }
    *     
    */
   public void setResourceContent(ResourceContentType value)
   {
      this.resourceContent = value;
   }

   /**
    * Gets the value of the attribute property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the attribute property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getAttribute().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link AttributeType }
    * 
    * 
    */
   public List<AttributeType> getAttribute()
   {
      if (attribute == null)
      {
         attribute = new ArrayList<AttributeType>();
      }
      return this.attribute;
   }

}
