//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.19 at 04:54:59 PM CDT 
//

package net.seagis.xacml.context;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.seagis.xacml.policy.ObligationsType;

/**
 * <p>Java class for ResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:context:schema:os}Decision"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:context:schema:os}Status" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:policy:schema:os}Obligations" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ResourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultType", propOrder =
{"decision", "status", "obligations"})
public class ResultType
{

   @XmlElement(name = "Decision", required = true)
   protected DecisionType decision;

   @XmlElement(name = "Status")
   protected StatusType status;

   @XmlElement(name = "Obligations", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os")
   protected ObligationsType obligations;

   @XmlAttribute(name = "ResourceId")
   protected String resourceId;

   /**
    * Gets the value of the decision property.
    * 
    * @return
    *     possible object is
    *     {@link DecisionType }
    *     
    */
   public DecisionType getDecision()
   {
      return decision;
   }

   /**
    * Sets the value of the decision property.
    * 
    * @param value
    *     allowed object is
    *     {@link DecisionType }
    *     
    */
   public void setDecision(DecisionType value)
   {
      this.decision = value;
   }

   /**
    * Gets the value of the status property.
    * 
    * @return
    *     possible object is
    *     {@link StatusType }
    *     
    */
   public StatusType getStatus()
   {
      return status;
   }

   /**
    * Sets the value of the status property.
    * 
    * @param value
    *     allowed object is
    *     {@link StatusType }
    *     
    */
   public void setStatus(StatusType value)
   {
      this.status = value;
   }

   /**
    * Gets the value of the obligations property.
    * 
    * @return
    *     possible object is
    *     {@link ObligationsType }
    *     
    */
   public ObligationsType getObligations()
   {
      return obligations;
   }

   /**
    * Sets the value of the obligations property.
    * 
    * @param value
    *     allowed object is
    *     {@link ObligationsType }
    *     
    */
   public void setObligations(ObligationsType value)
   {
      this.obligations = value;
   }

   /**
    * Gets the value of the resourceId property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getResourceId()
   {
      return resourceId;
   }

   /**
    * Sets the value of the resourceId property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setResourceId(String value)
   {
      this.resourceId = value;
   }

}
