//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.19 at 04:54:59 PM CDT 
//

package net.seagis.xacml.context;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for SubjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:xacml:2.0:context:schema:os}Attribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SubjectCategory" type="{http://www.w3.org/2001/XMLSchema}anyURI" default="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectType", propOrder =
{"attribute"})
public class SubjectType
{

   @XmlElement(name = "Attribute")
   protected List<AttributeType> attribute;

   @XmlAttribute(name = "SubjectCategory")
   @XmlSchemaType(name = "anyURI")
   protected String subjectCategory;

   /**
    * Gets the value of the attribute property.
    * 
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the attribute property.
    * 
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getAttribute().add(newItem);
    * </pre>
    * 
    * 
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link AttributeType }
    * 
    * 
    */
   public List<AttributeType> getAttribute()
   {
      if (attribute == null)
      {
         attribute = new ArrayList<AttributeType>();
      }
      return this.attribute;
   }

   /**
    * Gets the value of the subjectCategory property.
    * 
    * @return
    *     possible object is
    *     {@link String }
    *     
    */
   public String getSubjectCategory()
   {
      if (subjectCategory == null)
      {
         return "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject";
      }
      else
      {
         return subjectCategory;
      }
   }

   /**
    * Sets the value of the subjectCategory property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */
   public void setSubjectCategory(String value)
   {
      this.subjectCategory = value;
   }

}
