//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.11 at 08:02:10 PM CET 
//


package net.seagis.wcs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Definition of the spatial-temporal domain of a coverage. The Domain shall include a SpatialDomain (describing the spatial locations for which coverages can be requested), and should included a TemporalDomain (describing the time instants or intervals for which coverages can be requested). 
 * 
 * <p>Java class for CoverageDomainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoverageDomainType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpatialDomain" type="{http://www.opengis.net/wcs/1.1.1}SpatialDomainType"/>
 *         &lt;element ref="{http://www.opengis.net/wcs/1.1.1}TemporalDomain" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoverageDomainType", propOrder = {
    "spatialDomain",
    "temporalDomain"
})
public class CoverageDomainType {

    @XmlElement(name = "SpatialDomain", required = true)
    protected SpatialDomainType spatialDomain;
    @XmlElement(name = "TemporalDomain")
    protected TimeSequenceType temporalDomain;

    /**
     * Gets the value of the spatialDomain property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialDomainType }
     *     
     */
    public SpatialDomainType getSpatialDomain() {
        return spatialDomain;
    }

    /**
     * Sets the value of the spatialDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialDomainType }
     *     
     */
    public void setSpatialDomain(SpatialDomainType value) {
        this.spatialDomain = value;
    }

    /**
     * Although optional, the TemporalDomain should be included whenever a value is known or a useful estimate is available. 
     * 
     * @return
     *     possible object is
     *     {@link TimeSequenceType }
     *     
     */
    public TimeSequenceType getTemporalDomain() {
        return temporalDomain;
    }

    /**
     * Sets the value of the temporalDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSequenceType }
     *     
     */
    public void setTemporalDomain(TimeSequenceType value) {
        this.temporalDomain = value;
    }

}
