//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.11 at 08:02:10 PM CET 
//


package net.seagis.wcs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import net.seagis.gml.CodeType;


/**
 * This GridCRS is a simplification and specialization of a gml:DerivedCRS. All elements and attributes not required to define this GridCRS are optional. 
 * 
 * <p>Java class for GridCrsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridCrsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml}srsName" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wcs/1.1.1}GridBaseCRS"/>
 *         &lt;element ref="{http://www.opengis.net/wcs/1.1.1}GridType" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wcs/1.1.1}GridOrigin" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wcs/1.1.1}GridOffsets"/>
 *         &lt;element ref="{http://www.opengis.net/wcs/1.1.1}GridCS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.opengis.net/gml}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridCrsType", propOrder = {
    "srsName",
    "gridBaseCRS",
    "gridType",
    "gridOrigin",
    "gridOffsets",
    "gridCS"
})
public class GridCrsType {

    @XmlElement(namespace = "http://www.opengis.net/gml")
    protected CodeType srsName;
    @XmlElement(name = "GridBaseCRS", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String gridBaseCRS;
    @XmlElement(name = "GridType", defaultValue = "urn:ogc:def:method:WCS:1.1:2dSimpleGrid")
    @XmlSchemaType(name = "anyURI")
    protected String gridType;
    @XmlList
    @XmlElement(name = "GridOrigin", type = Double.class, defaultValue = "0 0")
    protected List<Double> gridOrigin;
    @XmlList
    @XmlElement(name = "GridOffsets", type = Double.class)
    protected List<Double> gridOffsets;
    @XmlElement(name = "GridCS", defaultValue = "urn:ogc:def:cs:OGC:0.0:Grid2dSquareCS")
    @XmlSchemaType(name = "anyURI")
    protected String gridCS;
    @XmlAttribute(namespace = "http://www.opengis.net/gml")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the srsName property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getSrsName() {
        return srsName;
    }

    /**
     * Sets the value of the srsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setSrsName(CodeType value) {
        this.srsName = value;
    }

    /**
     * Gets the value of the gridBaseCRS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridBaseCRS() {
        return gridBaseCRS;
    }

    /**
     * Sets the value of the gridBaseCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridBaseCRS(String value) {
        this.gridBaseCRS = value;
    }

    /**
     * When this GridType reference is omitted, the OperationMethod shall be the most commonly used method in a GridCRS, which is referenced by the default URN "urn:ogc:def:method:WCS:1.1:2dSimpleGrid". 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridType() {
        return gridType;
    }

    /**
     * Sets the value of the gridType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridType(String value) {
        this.gridType = value;
    }

    /**
     * When this GridOrigin position is omitted, the origin defaults be the most commonly used origin in a GridCRS used in the output part of a GetCapabilities operation request, namely "0 0". Gets the value of the gridOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gridOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGridOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getGridOrigin() {
        if (gridOrigin == null) {
            gridOrigin = new ArrayList<Double>();
        }
        return this.gridOrigin;
    }

    /**
     * Gets the value of the gridOffsets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gridOffsets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGridOffsets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getGridOffsets() {
        if (gridOffsets == null) {
            gridOffsets = new ArrayList<Double>();
        }
        return this.gridOffsets;
    }

    /**
     * When this GridCS reference is omitted, the GridCS defaults to the most commonly used grid coordinate system, which is referenced by the URN "urn:ogc:def:cs:OGC:0.0:Grid2dSquareCS". 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridCS() {
        return gridCS;
    }

    /**
     * Sets the value of the gridCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridCS(String value) {
        this.gridCS = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
