//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.11 at 08:02:10 PM CET 
//


package net.seagis.wcs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Identifier of a spatial interpolation method applicable to continuous grid coverages, plus the optional "null Resistance" parameter. 
 * 
 * <p>Java class for InterpolationMethodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterpolationMethodType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.opengis.net/wcs/1.1.1>InterpolationMethodBaseType">
 *       &lt;attribute name="nullResistance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterpolationMethodType")
public class InterpolationMethodType
    extends InterpolationMethodBaseType
{

    @XmlAttribute
    protected String nullResistance;

    /**
     * Gets the value of the nullResistance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNullResistance() {
        return nullResistance;
    }

    /**
     * Sets the value of the nullResistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNullResistance(String value) {
        this.nullResistance = value;
    }

}
