/*
 *    Constellation - An open source and standard compliant SDI
 *    http://www.constellation-sdi.org
 *
 *    (C) 2007 - 2008, Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.constellation.sos.io;

// J2SE dependencies
import java.io.File;
import java.util.List;

// JAXB dependencies
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

// Constellation dependencies
import org.constellation.gml.v311.DirectPositionType;
import org.constellation.sml.AbstractDerivableComponent;
import org.constellation.sml.AbstractSensorML;
import org.constellation.ws.WebServiceException;
import static org.constellation.ows.OWSExceptionCode.*;

/**
 *
 * @author Guilhem Legal (geomatys)
 */
public class FileSensorReader extends SensorReader {

    /**
     * A JAXB unmarshaller used to unmarshall the xml generated by the XMLWriter.
     */
    private Unmarshaller unmarshaller;

    private File dataDirectory;
    
    private String sensorIdBase;

    public FileSensorReader(File dataDirectory, String sensorIdBase) throws WebServiceException  {
        super();
        this.sensorIdBase = sensorIdBase;
        try {
            //we initialize the unmarshaller
            JAXBContext context = JAXBContext.newInstance("org.constellation.sml.v100:org.constellation.sml.v101");
            unmarshaller        = context.createUnmarshaller();

            this.dataDirectory  = dataDirectory;
        } catch (JAXBException ex) {
            ex.printStackTrace();
            throw new WebServiceException("JAXBException while starting the MDweb Senor reader", NO_APPLICABLE_CODE);
        } 
    }

    @Override
    public AbstractSensorML getSensor(String sensorId) throws WebServiceException {
        File sensorFile = new File(dataDirectory, sensorId + ".xml");
        if (sensorFile.exists()){
            try {
                Object unmarshalled = unmarshaller.unmarshal(sensorFile);
                if (unmarshalled instanceof JAXBElement) {
                    unmarshalled = ((JAXBElement) unmarshalled).getValue();
                }
                if (unmarshalled instanceof AbstractSensorML) {
                    return (AbstractSensorML) unmarshalled;
                } else {
                    throw new WebServiceException("The form unmarshalled is not a sensor", NO_APPLICABLE_CODE);
                }
            } catch (JAXBException ex) {
                ex.printStackTrace();
                throw new WebServiceException("JAXBException while unmarshalling the sensor", NO_APPLICABLE_CODE);
            }
        } else {
            throw new WebServiceException("this sensor is not registered in the database!",
                        INVALID_PARAMETER_VALUE, "procedure");
        }
    }

    @Override
    public DirectPositionType getSensorPosition(int formID) throws WebServiceException {
        AbstractSensorML sensor = getSensor(formID + "");
        if (sensor.getMember().size() == 1) {
            if (sensor.getMember().get(0) instanceof AbstractDerivableComponent) {
                AbstractDerivableComponent component = (AbstractDerivableComponent) sensor.getMember().get(0);
                if (component.getSMLLocation() != null && component.getSMLLocation().getPoint() != null &&
                    component.getSMLLocation().getPoint() != null && component.getSMLLocation().getPoint().getPos() != null)
                return component.getSMLLocation().getPoint().getPos();
            }
        }
        logger.severe("there is no piezo location");
        return null;
    }

    @Override
    public List<Integer> getNetworkIndex(int formID) throws WebServiceException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public String getNetworkName(int formID, String networkName) throws WebServiceException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public int getNewSensorId() throws WebServiceException {
        int maxID = 0;
        for (File f : dataDirectory.listFiles()) {
            String id = f.getName();
            id = id.substring(0, id.indexOf(".xml"));
            id = id.substring(id.indexOf(sensorIdBase) + sensorIdBase.length());
            try {
                int curentID = Integer.parseInt(id);
                if (curentID > maxID) {
                    maxID = curentID;
                }
            } catch (NumberFormatException ex) {
                throw new WebServiceException("unable to parse the identifier:" + id, NO_APPLICABLE_CODE);
            }
        }
        return maxID + 1;
    }

    @Override
    public void destroy() {
    }

}
